In [90]:
import pandas as pd

In [91]:
df_train = pd.read_csv('train.csv')
df_train.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1104,Acer,Aspire ES1-523,Notebook,15.6,1366x768,AMD A8-Series 7410 2.2GHz,4GB,500GB HDD,AMD Radeon R5,Windows 10,2.4kg,387.0
1,114,Dell,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7560U 2.4GHz,8GB,256GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.23kg,1379.0
2,172,Acer,Aspire A517-51G,Notebook,17.3,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Nvidia GeForce MX150,Windows 10,3kg,854.0
3,918,HP,Elitebook 820,Netbook,12.5,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.26kg,1483.0
4,447,Lenovo,IdeaPad 320-15AST,Notebook,17.3,1600x900,AMD A6-Series 9220 2.5GHz,8GB,1TB HDD,AMD Radeon R4,Windows 10,2.8kg,519.0

In [92]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         912 non-null    int64
 1   Company           912 non-null    object
 2   Product           912 non-null    object
 3   TypeName          912 non-null    object
 4   Inches            912 non-null    float64
 5   ScreenResolution  912 non-null    object
 6   Cpu               912 non-null    object
 7   Ram               912 non-null    object
 8   Memory            912 non-null    object
 9   Gpu               912 non-null    object
 10  OpSys             912 non-null    object
 11  Weight            912 non-null    object
 12  Price_euros       912 non-null    float64
dtypes: float64(2), int64(1), object(10)
memory usage: 92.8+ KB

## Cleaning data

In [88]:
df_train['Weight'] = df_train['Weight'].replace('kg', '', regex=True)

In [94]:
df_train[['Memory_size', 'Memory_type']] = df_train['Memory'].str.split(' + ', n=1, expand=True)
##df_train['Memory_size'] = #df_train['Memory_size'].replace('GB', '', regex=True)
#df_train['Memory_size'] = #df_train['Memory_size'].replace('.0', '', regex=True)
#df_train['Memory_size'] = #df_train['Memory_size'].replace('TB', '000', regex=True)
#df_train['Memory_size'] = #df_train['Memory_size'].astype(int)
#df_train1 = #df_train.drop(['Memory'], axis=1)
df_train1.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Memory_size,Memory_type,Resolution
0,1104,1,Aspire ES1-523,5,15.6,1049,AMD A8-Series 7410 2.2GHz,4,AMD Radeon R5,6,2.4,387.0,0,HDD,1049
1,114,2,XPS 13,4,13.3,Quad HD+ / Touchscreen 5760,Intel Core i7 7560U 2.4GHz,8,Intel Iris Plus Graphics 640,6,1.23,1379.0,256,SSD,5760
2,172,1,Aspire A517-51G,5,17.3,IPS Panel Full HD 2073,Intel Core i5 8250U 1.6GHz,8,Nvidia GeForce MX150,6,3,854.0,256,SSD,2073
3,918,3,Elitebook 820,3,12.5,Full HD 2073,Intel Core i7 7500U 2.7GHz,8,Intel HD Graphics 620,6,1.26,1483.0,512,SSD,2073
4,447,4,IdeaPad 320-15AST,5,17.3,8294,AMD A6-Series 9220 2.5GHz,8,AMD Radeon R4,6,2.8,519.0,1000,HDD,8294

In [85]:
df_train1['Memory_type'].unique()

array(['HDD', 'SSD', 'Hybrid', 'SSD +  1TB HDD', 'SSD +  500GB HDD',
       'Flash Storage', 'SSD +  256GB SSD', 'SSD +  2TB HDD',
       'HDD +  1TB HDD', 'Flash Storage +  1TB HDD', 'SSD +  512GB SSD'],
      dtype=object)

In [72]:
df_train1['Ram'] = df_train1['Ram'].replace('GB', '', regex=True)

In [73]:
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('1366x768', '1049', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('1440x900', '1296', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('1600x900', '8294', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('1920x1080', '2073', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('1920x1200', '2304', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('2160x1440', '3110', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('2304x1440', '3318', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('2256x1504', '3393', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('2560x1440', '3686', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('2560x1600', '4096', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('2880x1800', '5184', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('2400x1600', '3840', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('3200x1800', '5760', regex=True)
df_train1['ScreenResolution'] = df_train1['ScreenResolution'].replace('3840x2160', '8294', regex=True)

df_train1['ScreenResolution'].unique()

array(['1049', 'Quad HD+ / Touchscreen 5760', 'IPS Panel Full HD 2073',
       'Full HD 2073', '8294', 'IPS Panel Full HD / Touchscreen 2073',
       'IPS Panel Retina Display 3318', '4K Ultra HD / Touchscreen 8294',
       'Touchscreen 3686', 'Full HD / Touchscreen 2073', '1296',
       'IPS Panel Quad HD+ / Touchscreen 5760', 'Touchscreen 3393',
       'IPS Panel 4K Ultra HD / Touchscreen 8294',
       'IPS Panel Touchscreen / 4K Ultra HD 8294', 'IPS Panel 1049',
       '4K Ultra HD 8294', 'IPS Panel 4K Ultra HD 8294',
       'IPS Panel Retina Display 5184', 'IPS Panel Touchscreen 3686',
       'Touchscreen 1049', '3686', 'IPS Panel Retina Display 4096',
       'Quad HD+ 5760', 'IPS Panel Full HD 3686', '2073',
       'Touchscreen 3840', 'IPS Panel 3686', 'IPS Panel Quad HD+ 5760',
       'IPS Panel Touchscreen 1049', 'IPS Panel Touchscreen 2304',
       'Touchscreen / Quad HD+ 5760', 'IPS Panel Quad HD+ 3686',
       'IPS Panel Full HD 3110'], dtype=object)

In [74]:
df_train1['Resolution'] = df_train1['ScreenResolution'].str[-4:]

df_train1.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Memory_size,Memory_type,Resolution
0,1104,1,Aspire ES1-523,5,15.6,1049,AMD A8-Series 7410 2.2GHz,4,AMD Radeon R5,6,2.4,387.0,0,HDD,1049
1,114,2,XPS 13,4,13.3,Quad HD+ / Touchscreen 5760,Intel Core i7 7560U 2.4GHz,8,Intel Iris Plus Graphics 640,6,1.23,1379.0,256,SSD,5760
2,172,1,Aspire A517-51G,5,17.3,IPS Panel Full HD 2073,Intel Core i5 8250U 1.6GHz,8,Nvidia GeForce MX150,6,3,854.0,256,SSD,2073
3,918,3,Elitebook 820,3,12.5,Full HD 2073,Intel Core i7 7500U 2.7GHz,8,Intel HD Graphics 620,6,1.26,1483.0,512,SSD,2073
4,447,4,IdeaPad 320-15AST,5,17.3,8294,AMD A6-Series 9220 2.5GHz,8,AMD Radeon R4,6,2.8,519.0,1000,HDD,8294

In [77]:
df_train1["Memory_type"].unique()

array(['HDD', 'SSD', 'Hybrid', 'SSD +  1TB HDD', 'SSD +  500GB HDD',
       'Flash Storage', 'SSD +  256GB SSD', 'SSD +  2TB HDD',
       'HDD +  1TB HDD', 'Flash Storage +  1TB HDD', 'SSD +  512GB SSD'],
      dtype=object)

In [ ]:
#Numeric categorization of Memory_type
df_train1['Memory_type'] = df_train1['Memory_type'].replace(to_replace='', value=0, regex=True)
df_train1['Memory_type'] = df_train1['Memory_type'].replace(to_replace='', value=0, regex=True)

In [68]:
#Numeric categorization of TypeName
df_train1['OpSys'] = df_train1['OpSys'].replace(to_replace='No OS', value=0, regex=True)
df_train1['OpSys'] = df_train1['OpSys'].replace(to_replace='Linux', value=1, regex=True)
df_train1['OpSys'] = df_train1['OpSys'].replace(to_replace='Android', value=2, regex=True)
df_train1['OpSys'] = df_train1['OpSys'].replace(to_replace='Chrome OS', value=3, regex=True)
df_train1['OpSys'] = df_train1['OpSys'].replace(to_replace='Windows 7', value=4, regex=True)
df_train1['OpSys'] = df_train1['OpSys'].replace(to_replace='Windows 10 S', value=5, regex=True)
df_train1['OpSys'] = df_train1['OpSys'].replace(to_replace='Windows 10', value=6, regex=True)
df_train1['OpSys'] = df_train1['OpSys'].replace(to_replace='macOS', value=7, regex=True)
df_train1['OpSys'] = df_train1['OpSys'].replace(to_replace='Mac OS X', value=8, regex=True)
df_train1["OpSys"].unique()

array([6, 0, 1, 8, 4, 3, 7, 5, 2], dtype=int64)

In [58]:
#Numeric categorization of TypeName
df_train1['TypeName'] = df_train1['TypeName'].replace(to_replace='Workstation', value=6, regex=True)
df_train1['TypeName'] = df_train1['TypeName'].replace(to_replace='Notebook', value=5, regex=True)
df_train1['TypeName'] = df_train1['TypeName'].replace(to_replace='Ultrabook', value=4, regex=True)
df_train1['TypeName'] = df_train1['TypeName'].replace(to_replace='Netbook', value=3, regex=True)
df_train1['TypeName'] = df_train1['TypeName'].replace(to_replace='Gaming', value=2, regex=True)
df_train1['TypeName'] = df_train1['TypeName'].replace(to_replace='2 in 1 Convertible', value=1, regex=True)
df_train1['TypeName'].unique()

array([5, 4, 3, 2, 1, 6], dtype=int64)

In [64]:
#Numeric categorization of Company
df_train1['Company'] = df_train1['Company'].replace(to_replace='Acer', value=1, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Dell', value=2, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='HP', value=3, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Lenovo', value=4, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Asus', value=5, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Xiaomi', value=6, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Apple', value=7, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Samsung', value=8, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Razer', value=9, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Toshiba', value=10, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Fujitsu', value=11, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Microsoft', value=12, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='MSI', value=13, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='LG', value=14, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Mediacom', value=15, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Google', value=16, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Vero', value=17, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Huawei', value=18, regex=True)
df_train1['Company'] = df_train1['Company'].replace(to_replace='Chuwi', value=19, regex=True)


df_train1['Company'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int64)

In [75]:
df_train2 = df_train1.drop(['ScreenResolution', 'Product'], axis=1)
df_train2.head()

,laptop_ID,Company,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Memory_size,Memory_type,Resolution
0,1104,1,5,15.6,AMD A8-Series 7410 2.2GHz,4,AMD Radeon R5,6,2.4,387.0,0,HDD,1049
1,114,2,4,13.3,Intel Core i7 7560U 2.4GHz,8,Intel Iris Plus Graphics 640,6,1.23,1379.0,256,SSD,5760
2,172,1,5,17.3,Intel Core i5 8250U 1.6GHz,8,Nvidia GeForce MX150,6,3,854.0,256,SSD,2073
3,918,3,3,12.5,Intel Core i7 7500U 2.7GHz,8,Intel HD Graphics 620,6,1.26,1483.0,512,SSD,2073
4,447,4,5,17.3,AMD A6-Series 9220 2.5GHz,8,AMD Radeon R4,6,2.8,519.0,1000,HDD,8294

In [76]:
df_train2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   laptop_ID    912 non-null    int64
 1   Company      912 non-null    int64
 2   TypeName     912 non-null    int64
 3   Inches       912 non-null    float64
 4   Cpu          912 non-null    object
 5   Ram          912 non-null    object
 6   Gpu          912 non-null    object
 7   OpSys        912 non-null    int64
 8   Weight       912 non-null    object
 9   Price_euros  912 non-null    float64
 10  Memory_size  912 non-null    int32
 11  Memory_type  912 non-null    object
 12  Resolution   912 non-null    object
dtypes: float64(2), int32(1), int64(4), object(6)
memory usage: 89.2+ KB